# Runs only when changes are made to the workflow itself

on:
  pull_request:
    paths:
      - .github/workflows/check_cla.yml
      - reusable_workflows/check_cla/**
      - reusable_workflows/check_membership/**

jobs:
  call-check-cla:
    uses: dfinity/public-workflows/.github/workflows/check_cla.yml@master
